name: Publish Module

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare

      - name: Configure yarnrc.yml for authentication
        run: |
          echo "npmRegistries:
                  'https://npm.pkg.github.com':
                    npmAuthToken: ${{secrets.TOKEN}}" > ~/.yarnrc.yml

      - name: Publish
        run: yarn npm publish
