name: Publish Module

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --frozen-lockfile

      - name: Configure yarnrc.yml for authentication
        run: |
          echo "npmRegistries:
                  'https://npm.pkg.github.com':
                    npmAuthToken: ${{secrets.TOKEN}}" > ~/.yarnrc.yml

      - name: Publish
        run: yarn npm publish
